"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";

const metadata = {
  title: "Nirav",
  description: "Generated by create next app",
  icons: {
    icon: "https://png.pngtree.com/png-vector/20220207/ourmid/pngtree-e-letter-logo-ecommerce-shop-store-design-png-image_4381099.png",
  }
}


export default function RootLayout({ children }) {



  return (
    <Provider store={store}>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0"
          />
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </head>
        <body>
          <SessionProvider>
            {/* {!isAuthPage && <Navbar />} */}
            <Toaster />
            {children}
          </SessionProvider>
          {/* {!isAuthPage && <Footer />} */}
        </body>
      </html>
    </Provider>
  );
}
